# The URL the site will be built for
base_url = "https://zola-hacker.enginerd.io/"

# The title of the site
title = "k45514n's portfolio"

theme = "anemone"

# The description of the site
description = "Hacker is a theme for Zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = false

# Whether to generate an Atom feed
generate_feeds = true

# Taxonomies
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
[markdown.highlighting]
theme = "dark-plus"

# Whether to render emojis
render_emoji = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

[extra]
author = "Kassian Wren (k45514n)"
favicon = "favicon.ico"
list_pages = false
twitter_card = false
enable_search = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home/"},
  { url = "/resume", name_en = "/resume/" },
  { url = "/about", name_en = "/about/" },
  { url = "/blog", name_en = "/blog/" }
]
